package zenab.project.customerRelationshipManager.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.util.MultiValueMap;
import org.springframework.web.bind.annotation.*;
import zenab.project.customerRelationshipManager.entities.Customer;
import zenab.project.customerRelationshipManager.repositories.CustomerRepository;

@Controller
public class CustomerController {
    @RequestMapping("/addCustomer.html")
    public String firstPage() {
        return "addCustomer";
    }

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @PostMapping(path = "/add", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE) // Map ONLY POST Requests
    public @ResponseBody
    String addNewUser(@RequestBody MultiValueMap<String, String> formData) {
        // @ResponseBody means the returned String is the response, not a view firstName
        // @RequestParam means it is a parameter from the GET or POST request

        var firstName = formData.getFirst("first");
        var lastname = formData.getFirst("last");
        var email = formData.getFirst("email");

        Customer customer = new Customer();
        customer.setFirstName(firstName);
        customer.setLastName(lastname);
        customer.setEmail(email);
        customerRepository.save(customer);
        return "Saved! " + customer.getFirstName();
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Customer> getAllCustomers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }
}
